# Generated by Django 2.2.16 on 2022-05-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_confirmation_code'),
        ('users', '0002_auto_20220512_2218'),
    ]

    operations = [
    ]
