# Generated by Django 2.2.16 on 2022-05-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20220515_1024'),
        ('users', '0002_auto_20220514_0022'),
    ]

    operations = [
    ]
