# Generated by Django 2.2.16 on 2022-05-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20220515_1141'),
        ('users', '0005_merge_20220515_1134'),
    ]

    operations = [
    ]
